config/routes.rb
Geengo::Application.routes.draw do

  devise_for :users
  devise_for :employees, :controllers => {
    :registrations => "employees/registrations",
    :confirmations => "employees/confirmations"
  }

  get "/first_connection", :to => "first_connections#edit"
  put "/first_connection", :to => "first_connections#update"

  devise_scope :employee do
    get "/activation_pending", :to => "employees/registrations#activation_pending"
  end

  match "/firms/:id.css", :to => "firms#show", :format => "css"

  resources :administrative_documents, :only => [:create, :update, :destroy]
  resource :profile, :only => [:show, :update] do
    %w(perso password sports documents).each do |action|
      get "/#{action}", :action => action
    end
  end

  resources :messages, :only => [:create]

  match "/employees/valid_email", :to => "employees#valid_email"

  # custom rails_admin routes
  scope "/admin" do
    get "/employees"                  , :to => "rails_admin/employees#list"         , :model_name => "employees"
    post "/employees/bulk_action"     , :to => "rails_admin/employees#bulk_action"  , :model_name => "employees"
    get "/employees/:id/edit"         , :controller => "rails_admin/employees"      , :action => "edit"          , :model_name => "employees", :as => "edit_employee"
    put "/admins/:id"                 , :controller => "rails_admin/admins"         , :action => "update"        , :model_name => "admins"

    post "/:model_name"               , :controller => "rails_admin/imports"        , :action => "create"        , :constraints => {:model_name => /employees_imports|infrastructures_imports|events_imports/}
    get "/imports/:import_id/discards", :controller => "rails_admin/import_discards", :action => "list"          , :model_name => "import_discards"

    get "/user/:id/edit"              , :controller => "rails_admin/users"          , :action => "edit"          , :model_name => "user"
    put "/users/:id"                  , :controller => "rails_admin/users"          , :action => "update"        , :model_name => "users"
    get "/infrastructures/:id/edit"   , :controller => "rails_admin/infrastructures", :action => "edit"          , :model_name => "infrastructures"
    put "/infrastructures/:id"        , :controller => "rails_admin/infrastructures", :action => "update"        , :model_name => "infrastructures"

    mount Resque::Server, :at => "/resque"
    mount RailsAdmin::Engine => '/', :as => 'rails_admin'
  end

  match "/events", :to => "events#index", :as => "all_events"

  resources :sport_community_memberships, :only => [:create, :update, :destroy]

  scope "/:sport_name" do
    match "/community", :controller => "sport_communities", :action => "show", :as => :sport_community
    match "/community/members", :to => "members#index", :as => "community_members"
    resources :infrastructures, :only => [:index, :show]
    resources :events, :only => [:index, :show]
    match "/:parent_type/:parent_id/members", :to => "members#index"
    root :to => redirect("/%{sport_name}/community")
  end

  root :to => 'profiles#show'

end

app/controllers/profiles_controller.rb
# encoding : utf-8

class ProfilesController < FrontController

  # Actions
  #########

  def show
    @messages = current_employee.sport_communities.map(&:messages).inject({}) do |memo, messages|
      memo.merge(messages.arrange(:order => :updated_at))
    end

    sorted_messages = @messages.sort_by do |message, replies|
      message.updated_at
    end.reverse

    @messages = Hash[sorted_messages]

    render :layout => "application"
  end

  def perso
  end

  def password
  end

  def sports
    @my_memberhips = current_employee.sport_community_memberships.ordered_by_sport_name
  end

  def documents
    @doc = AdministrativeDocument.new
  end

  def update

    all_pwd_blank = [:current_password, :password, :password_confirmation].inject(true) do |memo, attribute|
      memo && params[:employee][attribute].blank?
    end

    result = if params[:employee][:current_password]
      current_employee.update_with_password(params[:employee])
    else
      current_employee.update_without_password(params[:employee])
    end

    referer_action = request.env["HTTP_REFERER"].split('/').last
    referer_action = %(perso password documents sports).include?(referer_action) ? referer_action : "perso"

    if result
      redirect_to "/profile/#{referer_action}", :notice => "Modifications enregistrées"
    else
      flash.now[:alert] = "Merci de corriger les erreurs suivantes"
      render referer_action
    end
  end

end

app/views/profiles/_flash.html.haml
- unless flash.empty?
  #flash
    - if flash[:notice]
      .alert-message.success.fade.in
        %a.close x
        %p= flash[:notice]

    - if flash[:alert]
      .alert-message.error.fade.in{"data-alert" => "alert"}
        %a.close x
        %p= flash[:alert]

app/views/profiles/_sections.html.haml
%ul.pills
  %li{:class => controller.action_name == "perso" ? "active" : nil}= link_to "Informations personnelles", "/profile/perso"
  %li{:class => controller.action_name == "password" ? "active" : nil}= link_to "Modification du mot de passe", "/profile/password"
  %li{:class => controller.action_name == "sports" ? "active" : nil}= link_to "Mes sports", "/profile/sports"
  %li{:class => controller.action_name == "documents" ? "active" : nil}= link_to "Documents administratifs", "/profile/documents"

app/views/profiles/documents.html.haml
%h3.title-module.wall Mes documents

- current_employee.documents.each do |doc|
      
  .modal.hide.fade{:id => "destroy-doc-#{doc.id}"}
    .modal-header
      %a.close{href: "#"} x
      %h3 Attention
    .modal-body
      %p Voulez-vous vraiment supprimer le document #{doc[:document]}
    .modal-footer
      = simple_form_for doc, :wrapper => :inline, :method => :delete, :html => {:style => "margin-bottom: 0px"} do |f|
        = hidden_field_tag :id => doc.id
        = f.submit "Confirmer", :class => "btn danger"

%table

  %tr
    %th Sport
    %th Type
    %th Document
    %th Etat
    %th

  - current_employee.documents.each do |doc|
    %tr
      %td
        %a{:href => sport_community_path(doc.sport_community_membership.sport_community.name.downcase)}
          .square-ico-small{:class => doc.sport_community_membership.sport_community.name.downcase, :rel => "twipsy", "data-original-title" => doc.sport_community_membership.sport_community.name}
      %td= best_in_place doc, :kind, :type => :select, :collection => I18n.t("activerecord.administrative_documents.kinds").stringify_keys.to_a, :display_as => :translated_kind
      %td= link_to doc[:document], doc.document.url, :target => "_blank"
      %td= doc.accepted? ? "Accepté" : "En attente de validation"
      %td
        %a{href: "#", "data-controls-modal" => "destroy-doc-#{doc.id}", "data-backdrop" => "true", "data-keyboard" => "true"}
          = image_tag "rails_admin/theme/activo/images/icons/24/cross.png", :alt => "Supprimer le document", :onmouseout => "this.src='/assets/rails_admin/theme/activo/images/icons/24/cross.png'", :onmouseover => "this.src='/assets/rails_admin/theme/activo/images/icons/24/cross-hover.png'", :rel => "twipsy", "data-original-title" => "Supprimer le document"

.modal.hide.fade{:id => "new-doc"}
  = simple_form_for current_employee.documents.build, :wrapper => :inline, :html => {:style => "margin-bottom: 0px"} do |f|
    .modal-header
      %a.close{href: "#"} x
      %h3 Ajouter un document
    .modal-body
      = f.association :sport_community_membership, :collection => current_employee.sport_community_memberships, :label => "Sport", :label_method => proc { |scm| scm.sport_community.name }, :include_blank => false
      = f.input :kind, :collection => f.object.availables_kinds, :include_blank => false
      = f.input :document
    .modal-footer
      = f.submit "Ajouter le document", class: "btn primary"

%a.btn.primary{href: "#", "data-controls-modal" => "new-doc", "data-backdrop" => "true", "data-keyboard" => "true"} Ajouter un document

app/views/profiles/password.html.haml
%h3.title-module.wall Modification du mot de passe

= simple_form_for current_employee, :wrapper => :inline, :url => profile_path do |f|

  = f.input :current_password, :label => "MdP actuel"
  = f.input :password
  = f.input :password_confirmation

  = f.submit "Enregistrer", class: "btn primary"

app/views/profiles/perso.html.haml
%h3.title-module.wall Informations personnelles

= simple_form_for current_employee, :wrapper => :inline, :url => profile_path do |f|
  
  .row
    .span6
      = f.input :first_name
      = f.input :last_name
      = f.input :department
      = f.input :address, input_html: {rows: "3"}
      = f.input :mobile

    .span6
      = image_tag current_employee.photo.main.url
      = f.file_field :photo

  = f.submit "Enregistrer", class: "btn primary"

app/views/profiles/show.html.haml
.row
  .span4
    #module-employee

      %h3.title-module Mon profil

      .background.back_employee

        = image_tag(current_employee.photo.main.url)

        %h5.subtitle Sports pratiqués

        - current_employee.sport_community_memberships.each do |scm|
          %a.box_sport.has-popover{:class => scm.sport_community.name.downcase, "data-original-title" => scm.sport_community.name, :href => sport_community_path(scm.sport_community.name.downcase)}
            = scm.sport_community.name
            .popover-content
              %dl
                %dt= "#{SportCommunityMembership.human_attribute_name(:level)}:"
                %dd= scm.tranlsated_level

                - [:position, :licence_number, :ranking].each do |attribute|
                  - if (value = scm.send(attribute)).present?
                    %dt= "#{SportCommunityMembership.human_attribute_name(attribute)}:"
                    %dd= value

      #module-myevents

        %h3.title-module Mon calendrier

        .background.back_myevents
          %span.label 17/10/11
          .myevent Match Cagival Olympic
          .circle-myevents.basketball

        .background.back_myevents
          %span.label 24/11/11
          .myevent Tournoi St-Orens/Labège
          .circle-myevents.tennis


  /* -------------------- [ MUR GENERAL : MES COMMUNAUTES SPORTIVES ] --------------------  */
  .span12
    %h3.title-module.wall Mes communautés sportives

    - @messages.each do |message, replies|
      = render "messages/thread", :message => message, :replies => replies.keys

app/views/profiles/sports.html.haml
%h3.title-module.wall Mes sports

- @my_memberhips.each do |scm|      
  .modal.hide.fade{:id => "destroy-scm-#{scm.id}"}
    .modal-header
      %a.close{href: "#"} x
      %h3 Attention
    .modal-body
      %p Voulez-vous vraiment quitter la communauté #{scm.sport_community.name}
      %p Si vous quittez cette communauté sportive, tous vos documents seront perdus.
    .modal-footer
      = simple_form_for scm, :wrapper => :inline, :method => :delete, :html => {:style => "margin-bottom: 0px"} do |f|
        = hidden_field_tag :id => scm.id
        = f.submit "Confirmer", :class => "btn danger"

%table
  %tr
    %th Sport
    %th Niveau
    %th Classement
    %th Poste
    %th Licence
    %th
    %th

  - @my_memberhips.each do |scm|
    %tr
      %td
        %a{:href => sport_community_path(scm.sport_community.name.downcase)}
          .square-ico-small{:class => scm.sport_community.name.downcase}
        = scm.sport_community.name
      %td= best_in_place scm, :level, :type => :select, :collection => I18n.t("activerecord.sport_community_membership.level").stringify_keys.to_a, :display_as => :tranlsated_level
      %td= best_in_place scm, :ranking
      %td= best_in_place scm, :position
      %td= best_in_place scm, :licence_number
      %td
        %a{href: "#", "data-controls-modal" => "destroy-scm-#{scm.id}", "data-backdrop" => "true", "data-keyboard" => "true"}
          = image_tag "rails_admin/theme/activo/images/icons/24/cross.png", :alt => "Quitter la communauté", :onmouseout => "this.src='/assets/rails_admin/theme/activo/images/icons/24/cross.png'", :onmouseover => "this.src='/assets/rails_admin/theme/activo/images/icons/24/cross-hover.png'", :rel => "twipsy", "data-original-title" => "Quitter la communauté"
  
%h3.title-module.wall Autres sports
= render :partial => "sport_community_memberships/new", :collection => @missing_communities, :as => :community

%table
  - @missing_communities.each do |sc|
    %tr
      %td
        %a{:href => sport_community_path(sc.name.downcase)}
          .square-ico-small{:class => sc.name.downcase}
        = sc.name
      %td
        %a.btn.primary{href: "#", "data-controls-modal" => "new-sc-#{sc.id}", "data-backdrop" => "true", "data-keyboard" => "true"} Devenir membre