config/routes.rb
Geengo::Application.routes.draw do

  devise_for :users
  devise_for :employees, :controllers => {
    :registrations => "employees/registrations",
    :confirmations => "employees/confirmations"
  }

  get "/first_connection", :to => "first_connections#edit"
  put "/first_connection", :to => "first_connections#update"

  devise_scope :employee do
    get "/activation_pending", :to => "employees/registrations#activation_pending"
  end

  match "/firms/:id.css", :to => "firms#show", :format => "css"

  resources :administrative_documents, :only => [:create, :update, :destroy]
  resource :profile, :only => [:show, :update] do
    %w(perso password sports documents).each do |action|
      get "/#{action}", :action => action
    end
  end

  resources :messages, :only => [:create]

  match "/employees/valid_email", :to => "employees#valid_email"

  # custom rails_admin routes
  scope "/admin" do
    get "/employees"                  , :to => "rails_admin/employees#list"         , :model_name => "employees"
    post "/employees/bulk_action"     , :to => "rails_admin/employees#bulk_action"  , :model_name => "employees"
    get "/employees/:id/edit"         , :controller => "rails_admin/employees"      , :action => "edit"          , :model_name => "employees", :as => "edit_employee"
    put "/admins/:id"                 , :controller => "rails_admin/admins"         , :action => "update"        , :model_name => "admins"

    post "/:model_name"               , :controller => "rails_admin/imports"        , :action => "create"        , :constraints => {:model_name => /employees_imports|infrastructures_imports|events_imports/}
    get "/imports/:import_id/discards", :controller => "rails_admin/import_discards", :action => "list"          , :model_name => "import_discards"

    get "/user/:id/edit"              , :controller => "rails_admin/users"          , :action => "edit"          , :model_name => "user"
    put "/users/:id"                  , :controller => "rails_admin/users"          , :action => "update"        , :model_name => "users"
    get "/infrastructures/:id/edit"   , :controller => "rails_admin/infrastructures", :action => "edit"          , :model_name => "infrastructures"
    put "/infrastructures/:id"        , :controller => "rails_admin/infrastructures", :action => "update"        , :model_name => "infrastructures"

    mount Resque::Server, :at => "/resque"
    mount RailsAdmin::Engine => '/', :as => 'rails_admin'
  end

  match "/events", :to => "events#index", :as => "all_events"

  resources :sport_community_memberships, :only => [:create, :update, :destroy]

  scope "/:sport_name" do
    match "/community", :controller => "sport_communities", :action => "show", :as => :sport_community
    match "/community/members", :to => "members#index", :as => "community_members"
    resources :infrastructures, :only => [:index, :show]
    resources :events, :only => [:index, :show]
    match "/:parent_type/:parent_id/members", :to => "members#index"
    root :to => redirect("/%{sport_name}/community")
  end

  root :to => 'profiles#show'

end

app/models/event.rb
# encoding: utf-8

class Event < ActiveRecord::Base

  # Module that handles services association and attributes
  include Purchasable

  # Associations
  ##############

  belongs_to :sport

  has_many :comments, :class_name => "Message", :as => :commentable, :dependent => :destroy

  # Validations
  #############

  validates :name, :presence => true
  validates :sport_id, :presence => true
  validates :starts_at, :presence => true
  validates :ends_at, :presence => true

  validate :ends_at_greater_than_starts_at

  # Validate :registration_ends_on and :broadcast_ends_on are greater than or equal to their
  # starts_on counterparts
  [:registration, :broadcast].each do |sym|
    validate do
      start_attribute = "#{sym}_starts_on"
      end_attribute = "#{sym}_ends_on"

      return unless (self.send(end_attribute) && self.send(start_attribute))

      message = I18n.t('errors.messages.greater_than_or_equal_to', :count => self.class.human_attribute_name(start_attribute))
      errors.add(end_attribute, message) unless self.send(end_attribute) >= self.send(start_attribute)
    end
  end

  validates :registration_email, :organizer_email, :format => {:with => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i, :allow_blank => true}

  validates :max_players_count, :max_team_players_count, :numericality => {:allow_nil => true}
  validates :venue_zip_code, :arrival_zip_code, :organizer_zip_code, :format => {:with => /^\d{5}$/, :allow_blank => true}

  validates :venue_phone, :organizer_phone, :format => {:with => /^\d{10}$/, :allow_blank => true}

  # Callbacks
  ###########

  after_validation :geocode, :if => :full_venue_address_changed?

  extend ImportUploaders

  # Geocoder
  ##########

  geocoded_by :full_venue_address
  acts_as_gmappable :process_geocoding => false

  # Scopes
  ########

  scope :featured, where(:featured => true)
  scope :non_featured, where(arel_table[:featured].eq(nil).or(arel_table[:featured].eq(false)))
  scope :published, Proc.new {
    where(
      arel_table[:broadcast_starts_on].lteq(Date.today),
      arel_table[:broadcast_ends_on].gteq(Date.today)
    )
  }
  scope :in_sliders, Proc.new {
    published.order(arel_table[:pfs_registration_ends_on].desc).limit(5)
  }

  # Instance methods
  ##################

  mount_uploader :brochure_image, EventBrochureUploader

  attr_accessible(
    :sport_name,
    :name,
    :starts_at,
    :ends_at,
    :description,
    :short_description,
    :target,
    :nature,
    :kind,
    :game_kind,
    :player_category,
    :participation_terms,
    :max_players_count,
    :max_team_players_count,
    :venue_name,
    :venue_phone,
    :venue_address,
    :venue_zip_code,
    :venue_city,
    :venue_country,
    :travel_informations,
    :arrival_address,
    :arrival_zip_code,
    :arrival_city,
    :arrival_country,
    :scale,
    :website_url,
    :registration_strategy,
    :payment_terms,
    :registration_starts_on,
    :registration_ends_on,
    :registration_email,
    :registration_mail,
    :practical_informations,
    :organizer_name,
    :organizer_contact,
    :organizer_phone,
    :organizer_email,
    :organizer_address,
    :organizer_zip_code,
    :organizer_city,
    :organizer_rib,
    :broadcast_starts_on,
    :broadcast_ends_on,
    :featured,
    :pfs_registration_ends_on
  )

  # Duration of the event
  # equals ends_at - starts_at
  def duration
    ends_at - starts_at
  end

  # setter used when importing
  # finds the sport with the given name and then sets the sport_id attribute on the infrastructure
  def sport_name=(name)
    sport = Sport.find_by_name(name)
    self.sport_id = sport.try(:id)
  end

  def full_venue_address
    part_1 = venue_address
    part_2 = [venue_zip_code, venue_city].reject(&:blank?).join(' ')
    part_3 = "France"
    [part_1, part_2, part_3].reject(&:blank?).join(', ')
  end

  protected

  def full_venue_address_changed?
    venue_address_changed? || venue_zip_code_changed? || venue_city_changed?
  end

  private

  def ends_at_greater_than_starts_at
    return unless (ends_at && starts_at)
    errors.add(:ends_at, "doit être supérieure à la date de début") unless ends_at > starts_at
  end

end

app/controllers/events_controller.rb
class EventsController < CommunityController

  # Actions
  #########

  def index
    redirect_to root_path if params[:sport_name].present? and current_community.nil?
    @events = current_community ? current_community.events.published : current_employee.firm.communities_events.published.all
  end

  def show
    @event = Event.find params[:id]
    @messages = @event.comments.arrange(:order => "updated_at desc")
  end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.haml
.event.row{:class => event.sport.name.downcase }
  .span1
    .square-ico
      
  .row
    .span11.event_name
      - Rails.logger.debug event.sport_id
      .bold= link_to event.name, event_path(event.sport.name.downcase, event.id)
      
      - if event.featured?
        %span.label.important.one A la une
   
    .span11
      .box_bgd
        .row
          .span3
            = image_tag event.brochure_image.url
            %a.btn.more{:href => event_path(event.sport.name.downcase, event.id)} En savoir plus
    
          .span7.informations
            %div.p= event.short_description

            / Dates
            %h5 Date
            %div.p= l(event.starts_at, :format => "%A %e %B %Y").titleize
            %h5 Fin d'inscription  
            %div.p= l(event.pfs_registration_ends_on, :format => "%A %e %B %Y").titleize if event.pfs_registration_ends_on

            / Adresse
            %h5 Lieu
            .p
              %div= event.venue_name
              %div= event.venue_address
              %span
                = event.venue_zip_code
                = event.venue_city

            / Conditions
            %h5 Conditions de participation
            %div.p= event.participation_terms
        
            .row
              .span11
                / les derniers inscrits
                %h5 Derniers inscrits
              
                %span{:href => "#", "data-original-title" => "Michelle Burta" , :rel => "twipsy"}
                  %img{:alt => "photo de Michelle Burta", :src => "/images/employees/burta_37.png"}
              
                %span{:href => "#", "data-original-title" => "Jean Dupont" , :rel => "twipsy"}
                  %img{:alt => "photo de Jean Dupont", :src => "/images/employees/dupont_37.png"}
            
                %span{:href => "#", "data-original-title" => "Pascal Yauru" , :rel => "twipsy"} 
                  %img{:alt => "photo de Pascal Yauru", :src => "/images/employees/yauru_37.png"}
            
                %span{:href => "#", "data-original-title" => "Mimi Outi" , :rel => "twipsy"}
                  %img{:alt => "photo de Mimi Outi", :src => "/images/employees/outi_37.png"}
              
                %span{:href => "#", "data-original-title" => "Michelle Arti" , :rel => "twipsy"}
                  %img{:alt => "photo de Michelle Arti", :src => "/images/employees/burta_37.png"}
              
                %span{:href => "#", "data-original-title" => "Jean Pouset" , :rel => "twipsy"}
                  %img{:alt => "photo de Jean Pouset", :src => "/images/employees/dupont_37.png"}
  
      

app/views/events/_event_slider.html.haml
.event_slider
  .event_circle{:class => "basketball"}
  
  %div
    %span.label.slider= event.featured? ? "A la une" : "Mes communautés"
    
  %div.box_slider 
    %div.affiche_slider= image_tag event.brochure_image.slider.url
  
  %div.box_slider.more
    %div.infos_slider
      %strong= event.name
      %br
      %em= event.sport.name
      %br
      = l(event.starts_at, :format => "%A %e %B %Y").titleize
      %br

      - if event.pfs_registration_ends_on
        %br
        .bold Inscriptions avant le
        = l(event.pfs_registration_ends_on, :format => "%A %e %B %Y").titleize
    
      
  %div.box_slider
    = link_to "M'inscrire", event_path(event.sport.name.downcase, event.id), :class => "btn registration"

app/views/events/_sliders.html.haml
- unless controller.is_a? EventsController

  .events
    .row
      .span16
        .row
          .span2
            %h3.title-module-actu Evénements

          .span4.link_events
            = link_to "Les voir tous", "/events"

    .row{:style => "margin-bottom: 10px;"}
      .span8
        #left-events-pager{:style => "float: right;"}
      .span8
        #featured-events-pager{:style => "float: right;"}

    .row
      .span8
        #left-events
          = render :partial => "events/event_slider", :collection => @my_communities_slider_events, :as => :event

      .span8
        #featured-events
          = render :partial => "events/event_slider", :collection => @featured_slider_events, :as => :event

app/views/events/index.html.haml
.row
  .span4
    %h3.title-module Rechercher
    
    .form_search
      %form
        %fieldset 
          %legend.bold Quand ?
          %ul
            %li
              %input.check{:type => "checkbox", :name => "my_home"} passés
            %li  
              %input.check{:type => "checkbox", :checked => "checked", :name => "my_company"} à venir
            %li 
              %input.check{:type => "checkbox", :name => "month"} mois de :
              %select.check.sel{:select => "select", :name => "month"}
                %option Janvier
                %option Février
                %option Mars
                %option Avril
                %option Mai
                %option Juin
                %option Juillet
                %option Août
                %option Septembre
                %option Octobre
                %option Novembre
                %option Décembre
                
        %fieldset
          %legend.bold Proche de ?
          %ul
            %li
              %input.check{:type => "checkbox", :name => "my_home"} mon domicile
            %li  
              %input.check{:type => "checkbox", :name => "my_company"} mon bureau
            %li 
              %input.check{:type => "checkbox", :name => "other"} autre adresse :
              %input.field_other_adress{:type => "text", :name => "other_adress"} 
        
          %button.btn.btn_search{:type => "submit"} Rechercher
                
  .span12
    %h3.title-module.wall Evénements

    = render @events

app/views/events/show.html.haml
.row
  .span4
    %h3.title-module Les tarifs
    
    %h3.title-module Les inscrits
    .members
      .member
        %img{:src => "/images/employees/dupont_37.png"}
        .identity
          %strong Jean Dupont
          %br/
          Matériel
    
      .member
        %img{:src => "/images/employees/yauru_37.png"}
        .identity
          %strong Pascal Yauru
          %br/
          Comptabilité
    
      .member
        %img{:src => "/images/employees/burta_37.png"}
        .identity
          %strong Michelle Burta
          %br/
          Ressources humaines
        
    %a.see_registered{:href => "#"} Voir tous les inscrits
  
  .span12
    %h3.title-module.wall Evénements
    
    .event.page{:class => current_community.name.downcase }
      .event_name.page.bold
        .row
          .span1
            .square-ico
          
          .span9.name
            = @event.name
            
          .span2
            - if @event.featured?
              %div.label.important.one.show A la une
      
      .row
        .span3
          .infra_picture
            = image_tag @event.brochure_image.url
            
        .span8
          .infra_description
            = @event.description
        
      .details
        %table
          %tr
            %td.title_details Date de début
            %td= l(@event.starts_at, :format => "%A %e %B %Y").titleize
          %tr
            %td.title_details Date de fin d'inscription
            %td= l(@event.pfs_registration_ends_on, :format => "%A %e %B %Y").titleize if @event.pfs_registration_ends_on
          %tr
            %td.title_details Heure de départ 
            %td= l(@event.starts_at, :format => "%Hh%M")
          %tr
            %td.title_details Contact de l'organisateur
            %td= @event.organizer_contact
          %tr
            %td.title_details Téléphone de l'organisateur
            %td= @event.organizer_phone
          %tr
            %td.title_details Email de l'organisateur
            %td= @event.organizer_email
          %tr
            %td.title_details Site internet
            %td= @event.website_url 
          %tr
            %td.title_details Conditions de participation
            %td= @event.participation_terms
      
      .title_line.bold Où ce trouve ce tournoi ?
      .row
        .span9
          = gmaps4rails(@event.to_gmaps4rails)
        
        .span3.adresse_page_event
          %p.bold Adresse
          %div= @event.venue_name
          %div= @event.venue_address
          = @event.venue_zip_code
          = @event.venue_city     

      .title_line.bold Commentaires
      
      = render "messages/share_form", :commentable => @event
      
      - @messages.each do |message, replies|
        = render "messages/thread", :message => message, :replies => replies.keys