config/routes.rb
Geengo::Application.routes.draw do

  devise_for :users
  devise_for :employees, :controllers => {
    :registrations => "employees/registrations",
    :confirmations => "employees/confirmations"
  }

  get "/first_connection", :to => "first_connections#edit"
  put "/first_connection", :to => "first_connections#update"

  devise_scope :employee do
    get "/activation_pending", :to => "employees/registrations#activation_pending"
  end

  match "/firms/:id.css", :to => "firms#show", :format => "css"

  resources :administrative_documents, :only => [:create, :update, :destroy]
  resource :profile, :only => [:show, :update] do
    %w(perso password sports documents).each do |action|
      get "/#{action}", :action => action
    end
  end

  resources :messages, :only => [:create]

  match "/employees/valid_email", :to => "employees#valid_email"

  # custom rails_admin routes
  scope "/admin" do
    get "/employees"                  , :to => "rails_admin/employees#list"         , :model_name => "employees"
    post "/employees/bulk_action"     , :to => "rails_admin/employees#bulk_action"  , :model_name => "employees"
    get "/employees/:id/edit"         , :controller => "rails_admin/employees"      , :action => "edit"          , :model_name => "employees", :as => "edit_employee"
    put "/admins/:id"                 , :controller => "rails_admin/admins"         , :action => "update"        , :model_name => "admins"

    post "/:model_name"               , :controller => "rails_admin/imports"        , :action => "create"        , :constraints => {:model_name => /employees_imports|infrastructures_imports|events_imports/}
    get "/imports/:import_id/discards", :controller => "rails_admin/import_discards", :action => "list"          , :model_name => "import_discards"

    get "/user/:id/edit"              , :controller => "rails_admin/users"          , :action => "edit"          , :model_name => "user"
    put "/users/:id"                  , :controller => "rails_admin/users"          , :action => "update"        , :model_name => "users"
    get "/infrastructures/:id/edit"   , :controller => "rails_admin/infrastructures", :action => "edit"          , :model_name => "infrastructures"
    put "/infrastructures/:id"        , :controller => "rails_admin/infrastructures", :action => "update"        , :model_name => "infrastructures"

    mount Resque::Server, :at => "/resque"
    mount RailsAdmin::Engine => '/', :as => 'rails_admin'
  end

  match "/events", :to => "events#index", :as => "all_events"

  resources :sport_community_memberships, :only => [:create, :update, :destroy]

  scope "/:sport_name" do
    match "/community", :controller => "sport_communities", :action => "show", :as => :sport_community
    match "/community/members", :to => "members#index", :as => "community_members"
    resources :infrastructures, :only => [:index, :show]
    resources :events, :only => [:index, :show]
    match "/:parent_type/:parent_id/members", :to => "members#index"
    root :to => redirect("/%{sport_name}/community")
  end

  root :to => 'profiles#show'

end

app/controllers/members_controller.rb
class MembersController < CommunityController

  def index
    @members = current_community.members.page(params[:page])
  end

end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_member.html.haml
- membership = member.sport_community_memberships.detect { |scm| scm.sport_community == current_community }

.employee_list
  .row
    .span4
      = image_tag member.photo.convers.url
      
      // lien à rendre dynamique pour accéder au profil d'un salarié
      %a{:href => "/profile/#{member.id}"} 
        %div.employee_name= member.name
      
    .span4
      .employee_infos= member.department
      
    .span4
      .employee_infos
        
      - current_employee.sport_community_memberships.each do |scm|
        // ajouter je pense dans la classe l'id employee pour n'afficher les sports d'un salarié (et pas sur tous les salariés ici)
        %a.has-popover.square-ico-small{:class => scm.sport_community.name.downcase, "data-original-title" => scm.sport_community.name, :href => sport_community_path(scm.sport_community.name.downcase)}

          .popover-content
            .table
              .infos_sports
                %table
                  %tr
                    %td.title_infos #{SportCommunityMembership.human_attribute_name(:level)}
                    %td= scm.tranlsated_level
                  %tr  
                    %td.title_infos #{SportCommunityMembership.human_attribute_name(:position)} 
                    %td= scm.position
                  %tr 
                    %td.title_infos #{SportCommunityMembership.human_attribute_name(:ranking)} 
                    %td= scm.ranking
                  %tr
                    %td.title_infos #{SportCommunityMembership.human_attribute_name(:licence_number)} 
                    %td= scm.licence_number
      
  .row
    .span12.border

app/views/members/_sidebar_member.html.haml
.member.sidebar

  = image_tag member.photo.convers.url
  .identity
    %strong= link_to member.name, "/profiles/#{member.id}"
    %br
    = member.department

app/views/members/index.html.haml
.row
  .span4
    %h3.title-module Rechercher
    %input{:type => "text", :value => "Nom et prénom du membre ?"}
    %button.btn.search{:type => "submit"} Rechercher
    
  .span12
    %h3.title-module.wall Membres de la communauté Tennis
    
    = render "sport_communities/join", :community => current_community, :title => "Rejoindre la communauté", :options => {:class => "btn primary"}
  
    = paginate @members
          
    .table
      .employees
        .row
          .span4
            %h5 Salarié
          .span4
            %h5 Service  
          .span4
            %h5 Ses communautés sportives
      
        .row
          .span12.border
          
        = render :partial => "members/member", :collection => @members
    
    = paginate @members